In [8]:
#Joseph Wanyoike Njoroge
#Date: 22nd May 2023
#Read the README.md to know more about this project

In [2]:
import pandas as pd

In [3]:
url = "https://aka.ms/diabetes-data" #This web file belongs to Microsoft.
data = pd.read_csv(url) #The dataset is used for Creating a classification model with Azure MLdesigner

In [5]:
data.to_csv("Diabetes-Classification.csv", index=False) #we save the dataset locally

In [6]:
data2 = pd.read_csv("Diabetes-Classification.csv")

In [7]:
data2

,PatientID,Pregnancies,PlasmaGlucose,DiastolicBloodPressure,TricepsThickness,SerumInsulin,BMI,DiabetesPedigree,Age,Diabetic
0,1354778,0,171,80,34,23,43.509726,1.213191,21,0
1,1147438,8,92,93,47,36,21.240576,0.158365,23,0
2,1640031,7,115,47,52,35,41.511523,0.079019,23,0
3,1883350,9,103,78,25,304,29.582192,1.282870,43,1
4,1424119,1,85,59,27,35,42.604536,0.549542,22,0
...,...,...,...,...,...,...,...,...,...,...
9995,1469198,6,95,85,37,267,18.497542,0.660240,31,0
9996,1432736,0,55,51,7,50,21.865341,0.086589,34,0
9997,1410962,5,99,59,47,67,30.774018,2.301594,43,1
9998,1958653,0,145,67,30,21,18.811861,0.789572,26,0
9999,1332938,10,100,54,34,27,38.840943,0.175465,23,0