In [1]:
#Joseph Wanyoike Njoroge
#Date: 22nd May 2023
#Read the README.md to know more about this project

In [2]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [3]:
url = "https://aka.ms/diabetes-data" #This web file belongs to Microsoft.
data = pd.read_csv(url) #The dataset is used for Creating a classification model with Azure MLdesigner

In [4]:
data.to_csv("Diabetes-Classification.csv", index=False) #we save the dataset locally

In [5]:
data2 = pd.read_csv("Diabetes-Classification.csv")

In [6]:
data2

,PatientID,Pregnancies,PlasmaGlucose,DiastolicBloodPressure,TricepsThickness,SerumInsulin,BMI,DiabetesPedigree,Age,Diabetic
0,1354778,0,171,80,34,23,43.509726,1.213191,21,0
1,1147438,8,92,93,47,36,21.240576,0.158365,23,0
2,1640031,7,115,47,52,35,41.511523,0.079019,23,0
3,1883350,9,103,78,25,304,29.582192,1.282870,43,1
4,1424119,1,85,59,27,35,42.604536,0.549542,22,0
...,...,...,...,...,...,...,...,...,...,...
9995,1469198,6,95,85,37,267,18.497542,0.660240,31,0
9996,1432736,0,55,51,7,50,21.865341,0.086589,34,0
9997,1410962,5,99,59,47,67,30.774018,2.301594,43,1
9998,1958653,0,145,67,30,21,18.811861,0.789572,26,0
9999,1332938,10,100,54,34,27,38.840943,0.175465,23,0

# Data Preprocessing (MinMax Normalization)

In [7]:
scaler = MinMaxScaler()

In [11]:
columns_to_normalize = ["Pregnancies", "PlasmaGlucose", "DiastolicBloodPressure", "TricepsThickness", "SerumInsulin", "BMI", "DiabetesPedigree", "Age"]

In [12]:
# Fit the scaler to the selected columns
scaler.fit(data[columns_to_normalize])

MinMaxScaler()

In [13]:
# Transform the selected columns by applying the scaler
data[columns_to_normalize] = scaler.transform(data[columns_to_normalize])

In [14]:
data

,PatientID,Pregnancies,PlasmaGlucose,DiastolicBloodPressure,TricepsThickness,SerumInsulin,BMI,DiabetesPedigree,Age,Diabetic
0,1354778,0.000000,0.858108,0.602151,0.317647,0.011509,0.668950,0.510511,0.000000,0
1,1147438,0.571429,0.324324,0.741935,0.470588,0.028133,0.080345,0.036123,0.035714,0
2,1640031,0.500000,0.479730,0.247312,0.529412,0.026854,0.616134,0.000438,0.035714,0
3,1883350,0.642857,0.398649,0.580645,0.211765,0.370844,0.300826,0.541848,0.392857,1
4,1424119,0.071429,0.277027,0.376344,0.235294,0.026854,0.645024,0.212047,0.017857,0
...,...,...,...,...,...,...,...,...,...,...
9995,1469198,0.428571,0.344595,0.655914,0.352941,0.323529,0.007843,0.261832,0.178571,0
9996,1432736,0.000000,0.074324,0.290323,0.000000,0.046036,0.096859,0.003843,0.232143,0
9997,1410962,0.357143,0.371622,0.376344,0.470588,0.067775,0.332327,1.000000,0.392857,1
9998,1958653,0.000000,0.682432,0.462366,0.270588,0.008951,0.016151,0.319997,0.089286,0
9999,1332938,0.714286,0.378378,0.322581,0.317647,0.016624,0.545547,0.043813,0.035714,0